spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/monitor-interface?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456

mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configuration:
            map-underscore-to-camel-case: true

logging:
  level:
    com:
      example:
        demo:
          module:
            dao: DEBUG